name: Android Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.2'
          java-package: jdk
          architecture: x64

      #      - name: Run Tests
      #        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble
