name: Run Instrumentation Tests

on:
  [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Run Instrumentation Tests (reactivecircus)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: Pixel XL
          script: ./gradlew connectedCheck
